import type { Metadata } from "next";


import React from "react";

import dynamic from "next/dynamic";
import Header from '~/components/Header'
import Sidebar from "~/components/Sidebar";
import ChatSideBar from "~/components/home/ChatSideBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    < >



      <div className={'md:flex w-screen  h-screen max-h-screen overflow-hidden  '}>
      <Sidebar/>

          {children}</div>
    </>

  );
}
