import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "~/components/NextUiProvider";
import React from "react";
import { cookies } from 'next/headers'
import {redirect} from "next/navigation";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    const hasToken= cookies().has("token")


  return (

    <html lang="en">

      <body className={inter.className + " bg-gray-50"}>
      <Provider>

          {children} </Provider></body>
    </html>

  );
}
